apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data
  namespace: sftpgo
  labels:
    app: sftpgo
    project: sftpgo-gke
  annotations:
    # GCP disk labels (applied to underlying GCE persistent disk)
    volume.beta.kubernetes.io/storage-labels: "app=sftpgo,project=sftpgo-gke"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-home
  namespace: sftpgo
  labels:
    app: sftpgo
    project: sftpgo-gke
  annotations:
    # GCP disk labels (applied to underlying GCE persistent disk)
    volume.beta.kubernetes.io/storage-labels: "app=sftpgo,project=sftpgo-gke"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard-rwo
